name: Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-dla-example:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Build examples
      working-directory: ./examples/hello-dla
      run: cargo build --examples
