name: Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-dla-example:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Build examples
      working-directory: ./examples/hello-dla
      run: cargo build --example dla
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dla-debug
        path: ./examples/hello-dla/target/riscv64imac-unknown-none-elf/debug/examples/dla
        if-no-files-found: error
        retention-days: 14

  run-dla-example:
    needs: build-dla-example

    runs-on: ubuntu-latest
    container:
      image: antmicro/renode:1.14.0
      ports:
      - 80
      volumes:
      - my_docker_volume:/volume_mount
      options: --user root
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dla-debug
        path: ./examples/hello-dla/dla
    - name: Run example
      working-directory: ./examples/hello-dla
      run: ./renode.sh dla
